### ISSUE TITLE
server crash when fire is missing?

### ISSUE THREAD

**Issue by sofar** [tenplus1/ambience#1]
Apr 11 23:45:58 clara minetestserver[14162]: 23:45:58: WARNING: Undeclared global variable "fire" accessed at /home/minetest/.minetest/mods/ambience/init.lua:135
Apr 11 23:45:58 clara minetestserver[14162]: 23:45:58: ERROR[main]: UNRECOVERABLE error occurred. Stopping server. Please fix the following error:
Apr 11 23:45:58 clara minetestserver[14162]: 23:45:58: ERROR[main]: /home/minetest/.minetest/mods/ambience/init.lua:135: attempt to index global 'fire' (a nil value)

**Comment by sofar** [comment]
diff --git a/init.lua b/init.lua
index 8077de6..f41c3ab 100644
--- a/init.lua
+++ b/init.lua
@@ -132,7 +132,7 @@ local get_ambience = function(player)
        end ; --print (num_fire, num_lava, num_water_flowing, num_water_source, num_desert)
 
        -- is fire redo mod active?
-   if fire.mod and fire.mod == "redo" then
+ if fire and fire.mod and fire.mod == "redo" then
                if num_fire > 8 then
                        return {largefire=largefire}
                elseif num_fire > 0 then

**Comment by tenplus1** [comment]
I never thought anyone wouldn't have a fire mod running, heh...  fixed...

**Comment by sofar** [comment]
I had it temporarily disabled due to having migrated my map from MC to 
MT, and lava/water conversion issues cause huge fires =)
