### ISSUE TITLE
Volume settings in config

### ISSUE THREAD

**Issue by yusf** [tenplus1/ambience#3]
It would be handy to be able to set the volume in the config file instead of changing mod code, since a git update could interfere with it.

**Comment by everamzah** [comment]
https://github.com/tenplus1/ambience/blob/master/init.lua#L338 Exists a chat command to set the volume, without the need for editing the mod.  You're asking for it to persist as a data file in the world path, I presume?

**Comment by yusf** [comment]
Correct! Perhaps in minetest.conf in such way as for example the irc mod does with `irc.server`, `irc.nick` and so on.

**Comment by BrunoMine** [comment]
This type of configuration is much more associated with the mod, not a specific world. I believe the best way is to save in minetest.conf.

**Comment by tenplus1** [comment]
By default ambience sounds play with normal minetest sounds, it's up to admin/player to use /svol command to lower/raise it when the need arises.
